/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sfml_dev_system_Clock */

#ifndef _Included_org_sfml_dev_system_Clock
#define _Included_org_sfml_dev_system_Clock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sfml_dev_system_Clock
 * Method:    getElapsedTime
 * Signature: ()Lorg/sfml_dev/system/Time;
 */
JNIEXPORT jobject JNICALL Java_org_sfml_1dev_system_Clock_getElapsedTime
  (JNIEnv *, jobject);

/*
 * Class:     org_sfml_dev_system_Clock
 * Method:    restart
 * Signature: ()Lorg/sfml_dev/system/Time;
 */
JNIEXPORT jobject JNICALL Java_org_sfml_1dev_system_Clock_restart
  (JNIEnv *, jobject);

/*
 * Class:     org_sfml_dev_system_Clock
 * Method:    getSizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_Clock_getSizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_system_Clock
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_Clock_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
